/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.databaseConnection;
import controller.centralController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ygpra
 */
public class addCustomer extends javax.swing.JPanel {

    private static final addCustomer addCust = new addCustomer();;

    /**
     * Creates new form addCustomer
     */
    private addCustomer() {
        initComponents();
        customerIdDisplay.setEditable(false);
        customerIdDisplay.setText(centralController.getInstance().getId("customer", "id", "C", "C001"));
    }

    public static addCustomer getAddCustomerInstance() {
        return addCust;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        forCustomerId = new javax.swing.JLabel();
        customerIdDisplay = new javax.swing.JTextField();
        forCustomerName = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        forAddress = new javax.swing.JLabel();
        inputAddress = new javax.swing.JTextField();
        forSalary = new javax.swing.JLabel();
        inputSalary = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 241, 255));

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(12, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Add Customer Form");

        forCustomerId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forCustomerId.setForeground(new java.awt.Color(12, 0, 0));
        forCustomerId.setText("Customer ID : ");

        customerIdDisplay.setBackground(new java.awt.Color(199, 200, 204));
        customerIdDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerIdDisplay.setForeground(new java.awt.Color(12, 0, 0));
        customerIdDisplay.setBorder(null);

        forCustomerName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forCustomerName.setForeground(new java.awt.Color(12, 0, 0));
        forCustomerName.setText("Customer Name : ");

        inputName.setBackground(new java.awt.Color(199, 200, 204));
        inputName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputName.setForeground(new java.awt.Color(12, 0, 0));
        inputName.setBorder(null);

        forAddress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forAddress.setForeground(new java.awt.Color(12, 0, 0));
        forAddress.setText("Address : ");

        inputAddress.setBackground(new java.awt.Color(199, 200, 204));
        inputAddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputAddress.setForeground(new java.awt.Color(12, 0, 0));
        inputAddress.setBorder(null);

        forSalary.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forSalary.setForeground(new java.awt.Color(12, 0, 0));
        forSalary.setText("Salary : ");

        inputSalary.setBackground(new java.awt.Color(199, 200, 204));
        inputSalary.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputSalary.setForeground(new java.awt.Color(12, 0, 0));
        inputSalary.setBorder(null);

        btnAdd.setBackground(new java.awt.Color(237, 150, 11));
        btnAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(239, 241, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(98, 99, 213));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(239, 241, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forCustomerName)
                            .addComponent(forAddress)
                            .addComponent(forCustomerId)
                            .addComponent(forSalary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIdDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 90, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(title)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forCustomerId)
                    .addComponent(customerIdDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forCustomerName)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forAddress)
                    .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forSalary)
                    .addComponent(inputSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // add customer
        try {
            String id = customerIdDisplay.getText();
            String name = inputName.getText();
            String address = inputAddress.getText();
            String salary = inputSalary.getText();

            String sql = "INSERT INTO customer VALUES(?,?,?,?)";

            databaseConnection dBConnection = databaseConnection.getInstance();
            Connection connection = dBConnection.getConnection();
            PreparedStatement stm = connection.prepareStatement(sql);
            stm.setString(1, id);
            stm.setString(2, name);
            stm.setString(3, address);
            stm.setString(4, salary);

            int res = stm.executeUpdate();
            if (res > 0) {
                String tempId = customerIdDisplay.getText();
                customerIdDisplay.setText(centralController.getInstance().getId("customer", "id", "C", "C001"));
                inputName.setText("");
                inputAddress.setText("");
                inputSalary.setText("");
                JOptionPane.showOptionDialog(null, tempId + " Customer Added is Successful.", "Success", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, centralController.successIcon, centralController.getInstance().getOkButton(), centralController.getInstance().getOkButton()[0]);
            } else {
                JOptionPane.showOptionDialog(null, "Failed! Has some issues with Adding " + id + " Customer.", "Error", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, centralController.errorIcon, centralController.getInstance().getOkButton(), centralController.getInstance().getOkButton()[0]);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showOptionDialog(null, ex.getMessage(), "Error", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, centralController.errorIcon, centralController.getInstance().getOkButton(), centralController.getInstance().getOkButton()[0]);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        inputName.setText("");
        inputAddress.setText("");
        inputSalary.setText("");
        
        addCust.setVisible(false);
        customerHome.getCustomerHomeInstance().setVisible(true);
        centralController.getInstance().enableNavBtn();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTextField customerIdDisplay;
    private javax.swing.JLabel forAddress;
    private javax.swing.JLabel forCustomerId;
    private javax.swing.JLabel forCustomerName;
    private javax.swing.JLabel forSalary;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputSalary;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
