/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author ygpra
 */
public class customerHome extends javax.swing.JPanel {
    
    private static final customerHome instance = new customerHome();
    private JPanel pagePanel;

    /**
     * Creates new form customerHome
     */
    private customerHome() {
        initComponents();
    }
    
    public static customerHome getCustomerHomeInstance(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 241, 255));

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(12, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Customer Page");

        btnAddCustomer.setBackground(new java.awt.Color(98, 99, 213));
        btnAddCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddCustomer.setForeground(new java.awt.Color(239, 241, 255));
        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.setBorder(null);
        btnAddCustomer.setBorderPainted(false);
        btnAddCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCustomer.setFocusPainted(false);
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerAction(evt);
            }
        });

        btnSearchCustomer.setBackground(new java.awt.Color(98, 99, 213));
        btnSearchCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearchCustomer.setForeground(new java.awt.Color(239, 241, 255));
        btnSearchCustomer.setText("Search Customer");
        btnSearchCustomer.setBorder(null);
        btnSearchCustomer.setBorderPainted(false);
        btnSearchCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchCustomer.setFocusPainted(false);
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(98, 99, 213));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(239, 241, 255));
        btnUpdate.setText("Update Customer");
        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(98, 99, 213));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(239, 241, 255));
        btnDelete.setText("Delete Customer");
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(98, 99, 213));
        btnView.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(239, 241, 255));
        btnView.setText("View Customers");
        btnView.setBorder(null);
        btnView.setBorderPainted(false);
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.setFocusPainted(false);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(title)
                .addGap(61, 61, 61)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        searchCustomer.getSearchCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(searchCustomer.getSearchCustomerInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        updateCustomer.getUpdateCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(updateCustomer.getUpdateCustomerInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        deleteCustomer.getDeleteCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(deleteCustomer.getDeleteCustomerInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        viewCustomers.getViewCustomersInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(viewCustomers.getViewCustomersInstance(), BorderLayout.CENTER);
        viewCustomers.getViewCustomersInstance().setTableInfo();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnAddCustomerAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        addCustomer.getAddCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(addCustomer.getAddCustomerInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnAddCustomerAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
