/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.centralController;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ygpra
 */
public class customerHome extends javax.swing.JPanel {
    
    private static final customerHome instance = new customerHome();
    private JPanel pagePanel;

    /**
     * Creates new form customerHome
     */
    private customerHome() {
        initComponents();
    }
    
    public static customerHome getCustomerHomeInstance(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        btnViewCustomers = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 241, 255));

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(12, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Customer Page");

        btnAddCustomer.setBackground(new java.awt.Color(98, 99, 213));
        btnAddCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddCustomer.setForeground(new java.awt.Color(239, 241, 255));
        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.setBorder(null);
        btnAddCustomer.setBorderPainted(false);
        btnAddCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCustomer.setFocusPainted(false);
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerAction(evt);
            }
        });

        btnSearchCustomer.setBackground(new java.awt.Color(98, 99, 213));
        btnSearchCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearchCustomer.setForeground(new java.awt.Color(239, 241, 255));
        btnSearchCustomer.setText("Search Customer");
        btnSearchCustomer.setBorder(null);
        btnSearchCustomer.setBorderPainted(false);
        btnSearchCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchCustomer.setFocusPainted(false);
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerAction(evt);
            }
        });

        btnUpdateCustomer.setBackground(new java.awt.Color(98, 99, 213));
        btnUpdateCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdateCustomer.setForeground(new java.awt.Color(239, 241, 255));
        btnUpdateCustomer.setText("Update Customer");
        btnUpdateCustomer.setBorder(null);
        btnUpdateCustomer.setBorderPainted(false);
        btnUpdateCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateCustomer.setFocusPainted(false);
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerAction(evt);
            }
        });

        btnDeleteCustomer.setBackground(new java.awt.Color(98, 99, 213));
        btnDeleteCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDeleteCustomer.setForeground(new java.awt.Color(239, 241, 255));
        btnDeleteCustomer.setText("Delete Customer");
        btnDeleteCustomer.setBorder(null);
        btnDeleteCustomer.setBorderPainted(false);
        btnDeleteCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteCustomer.setFocusPainted(false);
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerAction(evt);
            }
        });

        btnViewCustomers.setBackground(new java.awt.Color(98, 99, 213));
        btnViewCustomers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnViewCustomers.setForeground(new java.awt.Color(239, 241, 255));
        btnViewCustomers.setText("View Customers");
        btnViewCustomers.setBorder(null);
        btnViewCustomers.setBorderPainted(false);
        btnViewCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewCustomers.setFocusPainted(false);
        btnViewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomersAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(btnViewCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(206, 206, 206))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(61, 61, 61)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCustomerAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        searchCustomer.getSearchCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(searchCustomer.getSearchCustomerInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnSearchCustomerAction

    private void btnUpdateCustomerAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        updateCustomer.getUpdateCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(updateCustomer.getUpdateCustomerInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnUpdateCustomerAction

    private void btnDeleteCustomerAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        deleteCustomer.getDeleteCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(deleteCustomer.getDeleteCustomerInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnDeleteCustomerAction

    private void btnViewCustomersAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomersAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        viewCustomers.getViewCustomersInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(viewCustomers.getViewCustomersInstance(), BorderLayout.CENTER);
        viewCustomers.getViewCustomersInstance().setTableInfo();
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnViewCustomersAction

    private void btnAddCustomerAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        addCustomer.getAddCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(addCustomer.getAddCustomerInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnAddCustomerAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JButton btnViewCustomers;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
