/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.centralController;
import database.databaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ygpra
 */
public class deleteOrder extends javax.swing.JPanel {

    private static final deleteOrder instance = new deleteOrder();

    /**
     * Creates new form deleteOrder
     */
    private deleteOrder() {
        initComponents();
        btnDelete.setEnabled(false);
        btnSearch.setEnabled(true);
    }

    public static deleteOrder getDeleteOrderInstance() {
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        forOrderId = new javax.swing.JLabel();
        inputOrderId = new javax.swing.JTextField();
        forCustomerId = new javax.swing.JLabel();
        customerIdDisplay = new javax.swing.JLabel();
        forCustomerName = new javax.swing.JLabel();
        customerNameDisplay = new javax.swing.JLabel();
        forItem = new javax.swing.JLabel();
        itemNameDisplay = new javax.swing.JLabel();
        forQuantity = new javax.swing.JLabel();
        quantityDisplay = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        forTotal = new javax.swing.JLabel();
        totalDisplay = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 241, 255));

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(12, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Delete Order");

        forOrderId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forOrderId.setForeground(new java.awt.Color(12, 0, 0));
        forOrderId.setText("Enter Order ID :");

        inputOrderId.setBackground(new java.awt.Color(199, 200, 204));
        inputOrderId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputOrderId.setForeground(new java.awt.Color(12, 0, 0));
        inputOrderId.setBorder(null);

        forCustomerId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forCustomerId.setForeground(new java.awt.Color(12, 0, 0));
        forCustomerId.setText("Customer ID : ");

        customerIdDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerIdDisplay.setForeground(new java.awt.Color(12, 0, 0));
        customerIdDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        forCustomerName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forCustomerName.setForeground(new java.awt.Color(12, 0, 0));
        forCustomerName.setText("Customer Name : ");

        customerNameDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerNameDisplay.setForeground(new java.awt.Color(12, 0, 0));
        customerNameDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        forItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forItem.setForeground(new java.awt.Color(12, 0, 0));
        forItem.setText("Item : ");

        itemNameDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        itemNameDisplay.setForeground(new java.awt.Color(12, 0, 0));
        itemNameDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        forQuantity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forQuantity.setForeground(new java.awt.Color(12, 0, 0));
        forQuantity.setText("Quantity : ");

        quantityDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        quantityDisplay.setForeground(new java.awt.Color(12, 0, 0));
        quantityDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        btnDelete.setBackground(new java.awt.Color(231, 41, 41));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(239, 241, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAction(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(98, 99, 213));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(239, 241, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAction(evt);
            }
        });

        forTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forTotal.setForeground(new java.awt.Color(12, 0, 0));
        forTotal.setText("Total : ");

        totalDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        totalDisplay.setForeground(new java.awt.Color(12, 0, 0));
        totalDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        btnSearch.setBackground(new java.awt.Color(237, 150, 11));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(239, 241, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(forCustomerName)
                                    .addComponent(forCustomerId)
                                    .addComponent(forItem)
                                    .addComponent(forQuantity)
                                    .addComponent(forOrderId)
                                    .addComponent(forTotal))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerIdDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantityDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forOrderId)
                    .addComponent(inputOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forCustomerId)
                    .addComponent(customerIdDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forCustomerName)
                    .addComponent(customerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forItem)
                    .addComponent(itemNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forQuantity)
                            .addComponent(quantityDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forTotal)
                            .addComponent(totalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAction
        try {
            // delete order
            String id = inputOrderId.getText();
            String sql = "DELETE FROM orders WHERE id='" + id + "'";

            Connection connection = databaseConnection.getInstance().getConnection();
            Statement stm = connection.createStatement();
            stm.executeUpdate(sql);
            
            String orderId = inputOrderId.getText();

            inputOrderId.setText("");
            customerIdDisplay.setText("");
            customerNameDisplay.setText("");
            itemNameDisplay.setText("");
            quantityDisplay.setText("");
            totalDisplay.setText("");
            btnDelete.setEnabled(false);
            inputOrderId.setEditable(true);
            btnSearch.setEnabled(true);
            
            JOptionPane.showOptionDialog(null, orderId + " Order Delete is Successful.", "Success", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, centralController.successIcon, centralController.getInstance().getOkButton(), centralController.getInstance().getOkButton()[0]);

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showOptionDialog(null, ex.getMessage(), "Error", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, centralController.errorIcon, centralController.getInstance().getOkButton(), centralController.getInstance().getOkButton()[0]);
        }
    }//GEN-LAST:event_btnDeleteAction

    private void btnCancelAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAction
        inputOrderId.setText("");
        customerIdDisplay.setText("");
        customerNameDisplay.setText("");
        itemNameDisplay.setText("");
        quantityDisplay.setText("");
        totalDisplay.setText("");
        btnDelete.setEnabled(false);
        inputOrderId.setEditable(true);
        btnSearch.setEnabled(true);

        instance.setVisible(false);
        ordersHome.getOrdersHomeInstance().setVisible(true);
        centralController.getInstance().enableNavBtn();
    }//GEN-LAST:event_btnCancelAction

    private void btnSearchAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAction
        String orderId = inputOrderId.getText();
        displaySearchResult(orderId);
    }//GEN-LAST:event_btnSearchAction

    // display search result
    private void displaySearchResult(String orderId) {
        try {
            // search order
            ResultSet rst = centralController.getInstance().getOrder(orderId);
            rst.next();
            customerIdDisplay.setText(rst.getString("customerId"));

            // search customer
            ResultSet rstCustomer = centralController.getInstance().getCustomer(rst.getString("customerId"));
            rstCustomer.next();
            customerNameDisplay.setText(rstCustomer.getString("name"));

            // search order details
            ResultSet rstOrderDetails = centralController.getInstance().getOrderDetails(rst.getString("id"));
            rstOrderDetails.next();

            // search item
            ResultSet rstItem = centralController.getInstance().getItem(rstOrderDetails.getString("itemCode"));
            rstItem.next();

            itemNameDisplay.setText(rstItem.getString("description"));
            quantityDisplay.setText(rstOrderDetails.getString("qty"));

            int qty = Integer.parseInt(rstOrderDetails.getString("qty"));
            double unitPrice = Double.parseDouble(rstOrderDetails.getString("unitPrice"));

            String total = centralController.df.format(qty * unitPrice);
            totalDisplay.setText("Rs. " + total);
            btnDelete.setEnabled(true);
            inputOrderId.setEditable(false);
            btnSearch.setEnabled(false);

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showOptionDialog(null, ex.getMessage(), "Error", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, centralController.errorIcon, centralController.getInstance().getOkButton(), centralController.getInstance().getOkButton()[0]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel customerIdDisplay;
    private javax.swing.JLabel customerNameDisplay;
    private javax.swing.JLabel forCustomerId;
    private javax.swing.JLabel forCustomerName;
    private javax.swing.JLabel forItem;
    private javax.swing.JLabel forOrderId;
    private javax.swing.JLabel forQuantity;
    private javax.swing.JLabel forTotal;
    private javax.swing.JTextField inputOrderId;
    private javax.swing.JLabel itemNameDisplay;
    private javax.swing.JLabel quantityDisplay;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalDisplay;
    // End of variables declaration//GEN-END:variables
}
