/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JPanel;

/**
 *
 * @author ygpra
 */
public class itemHome extends javax.swing.JPanel {
    
    private static final itemHome instance = new itemHome();
    private JPanel pagePanel;

    /**
     * Creates new form itemHome
     */
    private itemHome() {
        initComponents();
    }
    
    public static itemHome getItemHomeInstance(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        btnSearchItem = new javax.swing.JButton();
        btnUpdateItem = new javax.swing.JButton();
        btnViewItems = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 241, 255));

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(12, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Item Page");

        btnAddItem.setBackground(new java.awt.Color(98, 99, 213));
        btnAddItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(239, 241, 255));
        btnAddItem.setText("Add Item");
        btnAddItem.setBorder(null);
        btnAddItem.setBorderPainted(false);
        btnAddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddItem.setFocusPainted(false);
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemAction(evt);
            }
        });

        btnSearchItem.setBackground(new java.awt.Color(98, 99, 213));
        btnSearchItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearchItem.setForeground(new java.awt.Color(239, 241, 255));
        btnSearchItem.setText("Search Item");
        btnSearchItem.setBorder(null);
        btnSearchItem.setBorderPainted(false);
        btnSearchItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchItem.setFocusPainted(false);
        btnSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchItemAction(evt);
            }
        });

        btnUpdateItem.setBackground(new java.awt.Color(98, 99, 213));
        btnUpdateItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdateItem.setForeground(new java.awt.Color(239, 241, 255));
        btnUpdateItem.setText("Update Item");
        btnUpdateItem.setBorder(null);
        btnUpdateItem.setBorderPainted(false);
        btnUpdateItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateItem.setFocusPainted(false);
        btnUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemAction(evt);
            }
        });

        btnViewItems.setBackground(new java.awt.Color(98, 99, 213));
        btnViewItems.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnViewItems.setForeground(new java.awt.Color(239, 241, 255));
        btnViewItems.setText("View Items");
        btnViewItems.setBorder(null);
        btnViewItems.setBorderPainted(false);
        btnViewItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewItems.setFocusPainted(false);
        btnViewItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewItemsAction(evt);
            }
        });

        btnDeleteItem.setBackground(new java.awt.Color(98, 99, 213));
        btnDeleteItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDeleteItem.setForeground(new java.awt.Color(239, 241, 255));
        btnDeleteItem.setText("Delete Item");
        btnDeleteItem.setBorder(null);
        btnDeleteItem.setBorderPainted(false);
        btnDeleteItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteItem.setFocusPainted(false);
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(btnSearchItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(61, 61, 61)
                .addComponent(btnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchItem, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateItem, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewItems, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteItem, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemAction
        /*pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        addCustomer.getAddCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(addCustomer.getAddCustomerInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();*/
    }//GEN-LAST:event_btnAddItemAction

    private void btnSearchItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchItemAction
        /*pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        searchCustomer.getSearchCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(searchCustomer.getSearchCustomerInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();*/
    }//GEN-LAST:event_btnSearchItemAction

    private void btnUpdateItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemAction
        /*pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        updateCustomer.getUpdateCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(updateCustomer.getUpdateCustomerInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();*/
    }//GEN-LAST:event_btnUpdateItemAction

    private void btnViewItemsAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewItemsAction
        /*pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        viewCustomers.getViewCustomersInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(viewCustomers.getViewCustomersInstance(), BorderLayout.CENTER);
        viewCustomers.getViewCustomersInstance().setTableInfo();
        centralController.getInstance().disableNavBtn();*/
    }//GEN-LAST:event_btnViewItemsAction

    private void btnDeleteItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemAction
        /*pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        deleteCustomer.getDeleteCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(deleteCustomer.getDeleteCustomerInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();*/
    }//GEN-LAST:event_btnDeleteItemAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnSearchItem;
    private javax.swing.JButton btnUpdateItem;
    private javax.swing.JButton btnViewItems;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
