/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author ygpra
 */
public class ordersHome extends javax.swing.JPanel {
    
    private static final ordersHome instance = new ordersHome();
    private JPanel pagePanel;

    /**
     * Creates new form ordersHome
     */
    private ordersHome() {
        initComponents();
    }
    
    public static ordersHome getOrdersHomeInstance(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddOrder = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 241, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(12, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Orders Page");

        btnAddOrder.setBackground(new java.awt.Color(98, 99, 213));
        btnAddOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddOrder.setForeground(new java.awt.Color(239, 241, 255));
        btnAddOrder.setText("Add Order");
        btnAddOrder.setBorder(null);
        btnAddOrder.setBorderPainted(false);
        btnAddOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddOrder.setFocusPainted(false);
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderAction(evt);
            }
        });

        btnSearchCustomer.setBackground(new java.awt.Color(98, 99, 213));
        btnSearchCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearchCustomer.setForeground(new java.awt.Color(239, 241, 255));
        btnSearchCustomer.setText("Search Order");
        btnSearchCustomer.setBorder(null);
        btnSearchCustomer.setBorderPainted(false);
        btnSearchCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchCustomer.setFocusPainted(false);
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(98, 99, 213));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(239, 241, 255));
        btnUpdate.setText("Update Order");
        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(98, 99, 213));
        btnView.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(239, 241, 255));
        btnView.setText("View Orders");
        btnView.setBorder(null);
        btnView.setBorderPainted(false);
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.setFocusPainted(false);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(98, 99, 213));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(239, 241, 255));
        btnDelete.setText("Delete Order");
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOrderAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        addOrder.getAddOrderInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(addOrder.getAddOrderInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnAddOrderAction

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        searchCustomer.getSearchCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(searchCustomer.getSearchCustomerInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        updateCustomer.getUpdateCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(updateCustomer.getUpdateCustomerInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        viewCustomers.getViewCustomersInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(viewCustomers.getViewCustomersInstance(), BorderLayout.CENTER);
        viewCustomers.getViewCustomersInstance().setTableInfo();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        deleteCustomer.getDeleteCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(deleteCustomer.getDeleteCustomerInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
