/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.centralController;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author ygpra
 */
public class ordersHome extends javax.swing.JPanel {
    
    private static final ordersHome instance = new ordersHome();
    private JPanel pagePanel;

    /**
     * Creates new form ordersHome
     */
    private ordersHome() {
        initComponents();
    }
    
    public static ordersHome getOrdersHomeInstance(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnAddOrder = new javax.swing.JButton();
        btnSearchOrder = new javax.swing.JButton();
        btnUpdateOrder = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 241, 255));

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(12, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Orders Page");

        btnAddOrder.setBackground(new java.awt.Color(98, 99, 213));
        btnAddOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddOrder.setForeground(new java.awt.Color(239, 241, 255));
        btnAddOrder.setText("Add Order");
        btnAddOrder.setBorder(null);
        btnAddOrder.setBorderPainted(false);
        btnAddOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddOrder.setFocusPainted(false);
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderAction(evt);
            }
        });

        btnSearchOrder.setBackground(new java.awt.Color(98, 99, 213));
        btnSearchOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearchOrder.setForeground(new java.awt.Color(239, 241, 255));
        btnSearchOrder.setText("Search Order");
        btnSearchOrder.setBorder(null);
        btnSearchOrder.setBorderPainted(false);
        btnSearchOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchOrder.setFocusPainted(false);
        btnSearchOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOrderAction(evt);
            }
        });

        btnUpdateOrder.setBackground(new java.awt.Color(98, 99, 213));
        btnUpdateOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdateOrder.setForeground(new java.awt.Color(239, 241, 255));
        btnUpdateOrder.setText("Update Order");
        btnUpdateOrder.setBorder(null);
        btnUpdateOrder.setBorderPainted(false);
        btnUpdateOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateOrder.setFocusPainted(false);
        btnUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderAction(evt);
            }
        });

        btnViewOrders.setBackground(new java.awt.Color(98, 99, 213));
        btnViewOrders.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnViewOrders.setForeground(new java.awt.Color(239, 241, 255));
        btnViewOrders.setText("View Orders");
        btnViewOrders.setBorder(null);
        btnViewOrders.setBorderPainted(false);
        btnViewOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewOrders.setFocusPainted(false);
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersAction(evt);
            }
        });

        btnDeleteOrder.setBackground(new java.awt.Color(98, 99, 213));
        btnDeleteOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDeleteOrder.setForeground(new java.awt.Color(239, 241, 255));
        btnDeleteOrder.setText("Delete Order");
        btnDeleteOrder.setBorder(null);
        btnDeleteOrder.setBorderPainted(false);
        btnDeleteOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteOrder.setFocusPainted(false);
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(btnViewOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(61, 61, 61)
                .addComponent(btnAddOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOrderAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        addOrder.getAddOrderInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(addOrder.getAddOrderInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnAddOrderAction

    private void btnSearchOrderAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOrderAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        searchOrder.getSearchOrderInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(searchOrder.getSearchOrderInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnSearchOrderAction

    private void btnUpdateOrderAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        updateOrder.getUpdateOrderInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(updateOrder.getUpdateOrderInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnUpdateOrderAction

    private void btnViewOrdersAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        viewOrders.getViewOrdersInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(viewOrders.getViewOrdersInstance(), BorderLayout.CENTER);
        viewOrders.getViewOrdersInstance().setTableInfo();
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnViewOrdersAction

    private void btnDeleteOrderAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        deleteOrder.getDeleteOrderInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(deleteOrder.getDeleteOrderInstance(), BorderLayout.CENTER);
        centralController.getInstance().disableNavBtn();
    }//GEN-LAST:event_btnDeleteOrderAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnSearchOrder;
    private javax.swing.JButton btnUpdateOrder;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
