/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author ygpra
 */
public class ordersHome extends javax.swing.JPanel {
    
    private static final ordersHome instance = new ordersHome();
    private JPanel pagePanel;

    /**
     * Creates new form ordersHome
     */
    private ordersHome() {
        initComponents();
    }
    
    public static ordersHome getOrdersHomeInstance(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnAddOrder = new javax.swing.JButton();
        btnSearchOrder = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 241, 255));

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(12, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Orders Page");

        btnAddOrder.setBackground(new java.awt.Color(98, 99, 213));
        btnAddOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddOrder.setForeground(new java.awt.Color(239, 241, 255));
        btnAddOrder.setText("Add Order");
        btnAddOrder.setBorder(null);
        btnAddOrder.setBorderPainted(false);
        btnAddOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddOrder.setFocusPainted(false);
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderAction(evt);
            }
        });

        btnSearchOrder.setBackground(new java.awt.Color(98, 99, 213));
        btnSearchOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearchOrder.setForeground(new java.awt.Color(239, 241, 255));
        btnSearchOrder.setText("Search Order");
        btnSearchOrder.setBorder(null);
        btnSearchOrder.setBorderPainted(false);
        btnSearchOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchOrder.setFocusPainted(false);
        btnSearchOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOrderAction(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(98, 99, 213));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(239, 241, 255));
        btnUpdate.setText("Update Order");
        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAction(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(98, 99, 213));
        btnView.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(239, 241, 255));
        btnView.setText("View Orders");
        btnView.setBorder(null);
        btnView.setBorderPainted(false);
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.setFocusPainted(false);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAction(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(98, 99, 213));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(239, 241, 255));
        btnDelete.setText("Delete Order");
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(61, 61, 61)
                .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOrderAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        addOrder.getAddOrderInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(addOrder.getAddOrderInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnAddOrderAction

    private void btnSearchOrderAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOrderAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        searchOrder.getSearchOrderInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(searchOrder.getSearchOrderInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnSearchOrderAction

    private void btnUpdateAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        updateOrder.getUpdateOrderInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(updateOrder.getUpdateOrderInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnUpdateAction

    private void btnViewAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAction
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        viewOrders.getViewOrdersInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(viewOrders.getViewOrdersInstance(), BorderLayout.CENTER);
        viewOrders.getViewOrdersInstance().setTableInfo();
    }//GEN-LAST:event_btnViewAction

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        pagePanel = dashboard.getHomeInstance().getPagePanel();
        instance.setVisible(false);
        deleteCustomer.getDeleteCustomerInstance().setVisible(true);
        pagePanel.setLayout(new BorderLayout());
        pagePanel.add(deleteCustomer.getDeleteCustomerInstance(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchOrder;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
