/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.centralController;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ygpra
 */
public class searchOrder extends javax.swing.JPanel {

    private static final searchOrder instance = new searchOrder();

    /**
     * Creates new form searchOrder
     */
    private searchOrder() {
        initComponents();
    }

    public static searchOrder getSearchOrderInstance() {
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        forOrderId = new javax.swing.JLabel();
        orderIdInput = new javax.swing.JTextField();
        forCustomerId = new javax.swing.JLabel();
        customerIdDisplay = new javax.swing.JLabel();
        forCustomerName = new javax.swing.JLabel();
        customerNameDisplay = new javax.swing.JLabel();
        forItem = new javax.swing.JLabel();
        itemDisplay = new javax.swing.JLabel();
        forQty = new javax.swing.JLabel();
        qtyDisplay = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        forTotal = new javax.swing.JLabel();
        totalDisplay = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 241, 255));

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(12, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Search Order");

        forOrderId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forOrderId.setForeground(new java.awt.Color(12, 0, 0));
        forOrderId.setText("Enter Order ID :");

        orderIdInput.setBackground(new java.awt.Color(199, 200, 204));
        orderIdInput.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        orderIdInput.setForeground(new java.awt.Color(12, 0, 0));
        orderIdInput.setBorder(null);

        forCustomerId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forCustomerId.setForeground(new java.awt.Color(12, 0, 0));
        forCustomerId.setText("Customer ID : ");

        customerIdDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerIdDisplay.setForeground(new java.awt.Color(12, 0, 0));
        customerIdDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        forCustomerName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forCustomerName.setForeground(new java.awt.Color(12, 0, 0));
        forCustomerName.setText("Customer Name : ");

        customerNameDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerNameDisplay.setForeground(new java.awt.Color(12, 0, 0));
        customerNameDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        forItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forItem.setForeground(new java.awt.Color(12, 0, 0));
        forItem.setText("Item : ");

        itemDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        itemDisplay.setForeground(new java.awt.Color(12, 0, 0));
        itemDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        forQty.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forQty.setForeground(new java.awt.Color(12, 0, 0));
        forQty.setText("Quantity : ");

        qtyDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        qtyDisplay.setForeground(new java.awt.Color(12, 0, 0));
        qtyDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        btnSearch.setBackground(new java.awt.Color(237, 150, 11));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(239, 241, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAction(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(98, 99, 213));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(239, 241, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAction(evt);
            }
        });

        forTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forTotal.setForeground(new java.awt.Color(12, 0, 0));
        forTotal.setText("Total : ");

        totalDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        totalDisplay.setForeground(new java.awt.Color(12, 0, 0));
        totalDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forCustomerName)
                            .addComponent(forCustomerId)
                            .addComponent(forItem)
                            .addComponent(forQty)
                            .addComponent(forTotal)
                            .addComponent(forOrderId))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(qtyDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orderIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerIdDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 26, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forOrderId)
                    .addComponent(orderIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forCustomerId)
                    .addComponent(customerIdDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forCustomerName)
                    .addComponent(customerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forItem)
                    .addComponent(itemDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forQty)
                            .addComponent(qtyDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forTotal)
                            .addComponent(totalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAction
        try {
            // search order
            String id = orderIdInput.getText();
            ResultSet rst = centralController.getInstance().getOrder(id);
            rst.next();
            customerIdDisplay.setText(rst.getString("customerId"));

            // search customer
            ResultSet rstCustomer = centralController.getInstance().getCustomer(rst.getString("customerId"));
            rstCustomer.next();
            customerNameDisplay.setText(rstCustomer.getString("name"));

            // search order details
            ResultSet rstOrderDetails = centralController.getInstance().getOrderDetails(rst.getString("id"));
            rstOrderDetails.next();

            // search item
            ResultSet rstItem = centralController.getInstance().getItem(rstOrderDetails.getString("itemCode"));
            rstItem.next();

            itemDisplay.setText(rstItem.getString("description"));
            qtyDisplay.setText(rstOrderDetails.getString("qty"));

            int qty = Integer.parseInt(rstOrderDetails.getString("qty"));
            double unitPrice = Double.parseDouble(rstOrderDetails.getString("unitPrice"));

            String total = centralController.df.format(qty * unitPrice);
            totalDisplay.setText("Rs. " + total);

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showOptionDialog(null, ex.getMessage(), "Error", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, centralController.errorIcon, centralController.getInstance().getOkButton(), centralController.getInstance().getOkButton()[0]);
        }
    }//GEN-LAST:event_btnSearchAction

    private void btnCancelAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAction
        orderIdInput.setText("");
        customerIdDisplay.setText("");
        customerNameDisplay.setText("");
        itemDisplay.setText("");
        qtyDisplay.setText("");
        totalDisplay.setText("");

        instance.setVisible(false);
        ordersHome.getOrdersHomeInstance().setVisible(true);
        centralController.getInstance().enableNavBtn();
    }//GEN-LAST:event_btnCancelAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel customerIdDisplay;
    private javax.swing.JLabel customerNameDisplay;
    private javax.swing.JLabel forCustomerId;
    private javax.swing.JLabel forCustomerName;
    private javax.swing.JLabel forItem;
    private javax.swing.JLabel forOrderId;
    private javax.swing.JLabel forQty;
    private javax.swing.JLabel forTotal;
    private javax.swing.JLabel itemDisplay;
    private javax.swing.JTextField orderIdInput;
    private javax.swing.JLabel qtyDisplay;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalDisplay;
    // End of variables declaration//GEN-END:variables
}
