/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.centralController;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ygpra
 */
public class searchItem extends javax.swing.JPanel {
    
    private static final searchItem instance = new searchItem();

    /**
     * Creates new form searchItem
     */
    private searchItem() {
        initComponents();
    }
    
    public static searchItem getSearchItemInstance(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        forItemCode = new javax.swing.JLabel();
        itemCodeInput = new javax.swing.JTextField();
        forDescription = new javax.swing.JLabel();
        descriptionDisplay = new javax.swing.JLabel();
        forUnitPrice = new javax.swing.JLabel();
        unitPriceDisplay = new javax.swing.JLabel();
        forQtyOnHand = new javax.swing.JLabel();
        qtyOnHandDisplay = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 241, 255));

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(12, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Search Item");

        forItemCode.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forItemCode.setForeground(new java.awt.Color(12, 0, 0));
        forItemCode.setText("Enter Item Code :");

        itemCodeInput.setBackground(new java.awt.Color(199, 200, 204));
        itemCodeInput.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        itemCodeInput.setForeground(new java.awt.Color(12, 0, 0));
        itemCodeInput.setBorder(null);

        forDescription.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forDescription.setForeground(new java.awt.Color(12, 0, 0));
        forDescription.setText("Description : ");

        descriptionDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        descriptionDisplay.setForeground(new java.awt.Color(12, 0, 0));
        descriptionDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        forUnitPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forUnitPrice.setForeground(new java.awt.Color(12, 0, 0));
        forUnitPrice.setText("Unit Price : ");

        unitPriceDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        unitPriceDisplay.setForeground(new java.awt.Color(12, 0, 0));
        unitPriceDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        forQtyOnHand.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        forQtyOnHand.setForeground(new java.awt.Color(12, 0, 0));
        forQtyOnHand.setText("Qty On Hand : ");

        qtyOnHandDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        qtyOnHandDisplay.setForeground(new java.awt.Color(12, 0, 0));
        qtyOnHandDisplay.setMaximumSize(new java.awt.Dimension(0, 24));

        btnSearch.setBackground(new java.awt.Color(237, 150, 11));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(239, 241, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAction(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(98, 99, 213));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(239, 241, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forUnitPrice)
                    .addComponent(forDescription)
                    .addComponent(forQtyOnHand)
                    .addComponent(forItemCode))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(qtyOnHandDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(unitPriceDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forItemCode)
                    .addComponent(itemCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forDescription)
                    .addComponent(descriptionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forUnitPrice)
                    .addComponent(unitPriceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forQtyOnHand)
                    .addComponent(qtyOnHandDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAction
        try {
            // search item
            String code = itemCodeInput.getText();
            ResultSet rst = centralController.getInstance().getItem(code);
            rst.next();
            descriptionDisplay.setText(rst.getString("description"));
            unitPriceDisplay.setText("Rs. "+rst.getString("unitPrice"));
            qtyOnHandDisplay.setText(rst.getString("qtyOnHand"));

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showOptionDialog(null, ex.getMessage(), "Error", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, centralController.errorIcon, centralController.getInstance().getOkButton(), centralController.getInstance().getOkButton()[0]);
        }
    }//GEN-LAST:event_btnSearchAction

    private void btnCancelAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAction
        itemCodeInput.setText("");
        descriptionDisplay.setText("");
        unitPriceDisplay.setText("");
        qtyOnHandDisplay.setText("");

        instance.setVisible(false);
        itemHome.getItemHomeInstance().setVisible(true);
        centralController.getInstance().enableNavBtn();
    }//GEN-LAST:event_btnCancelAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel descriptionDisplay;
    private javax.swing.JLabel forDescription;
    private javax.swing.JLabel forItemCode;
    private javax.swing.JLabel forQtyOnHand;
    private javax.swing.JLabel forUnitPrice;
    private javax.swing.JTextField itemCodeInput;
    private javax.swing.JLabel qtyOnHandDisplay;
    private javax.swing.JLabel title;
    private javax.swing.JLabel unitPriceDisplay;
    // End of variables declaration//GEN-END:variables
}
